### PR TITLE
Default as string parameter in config

### PR DESCRIPTION
**Pull request by norin89**
@tonai, first of all thanks for your great work on this addon!

I'm switching from [@storybook/addon-backgrounds](https://github.com/storybookjs/storybook/tree/next/addons/backgrounds) you wrote you were inspired by. It seems that your addon fills for me missing gaps in `@storybook/addon-backgrounds`.

Description
----
In my changes `default` option is a string on configuration object, not `boolean` on Theme object as previously. It's done the same way as in `@storybook/addon-backgrounds` ([link to configuration](https://storybook.js.org/docs/react/essentials/backgrounds#configuration)) and allows to set different default theme for each Story, without overriding whole `list`.

Due to that change I removed ability to pass themes array directly in `themes` parameter in favour to "full" config object (including `list` array). It's possible to reverse and fix that part for backward compatibility but two `default` values might be confusing. I can take a look at this if you don't plan to make major release and backward compatibility is crucial.

### CODE REVIEW

**Comment by tonai** [comment]
Hi @norin89 , thank you for your PR.
Removing the `default` parameter in the theme object and use a `default` parameter in the configuration object with a string seems ok for me as you can only have one default theme.
But I think removing the ability to pass directly a list of theme direcly when configuring the addon (and not the full `ThemeConfig` object) is a big loss, and don't really get the point why you wanted to remove it.
There is no two default when I see this:
```
{
  default: 'twitter',
  list: [
    { name: 'twitter', class: 'theme-twt', color: '#00aced' },
    { name: 'facebook', class: 'theme-fb', color: '#3b5998' }
  ],
}
```
I would prefer to have backward compatibility for that and still be able to pass a config object that is only:
```
[
  { name: 'twitter', class: 'theme-twt', color: '#00aced' },
  { name: 'facebook', class: 'theme-fb', color: '#3b5998' }
],
```

**Comment by norin89** [comment]
I refactored the code without thinking of backward compatibility. **I can fix that!**

Would you like to preserve `default` option on Theme object for full backward compatibility? What about this case:
<pre>
{
  <b>default: 'twitter'</b>,
  list: [
    { name: 'twitter', class: 'theme-twt', color: '#00aced' },
    { name: 'facebook', class: 'theme-fb', color: '#3b5998', <b>default: true</b> }
  ],
}
</pre>
IMO `default: 'twitter'` should be prioritised over `default: true` as it still allows to overwrite only the default theme in specified story even if some other theme is marked as `default: true`.

**Comment by tonai** [comment]
Yes you are right we can go like this and deprecate the `default` option, that is a boolean.
We will remove that option later.
In that case the `default` option, that is a string as priority over the deprecated one.

**Comment by norin89** [comment]
@tonai sorry for the delay. I've restored `default` (`boolean`) parameter on `Theme` object. So now there's a full backward compatibility. I've also resolved all the conflicts in Readme and updated it.

**Comment by tonai** [comment]
Thank you @norin89 for your PR.
There is just one thing left.
I recently merged a PR that adds a html decorator, can you update that file too ? (https://github.com/tonai/storybook-addon-themes/blob/master/src/decorators/html.ts)
Thanks a lot

**Comment by norin89** [comment]
@tonai sure, done. :)

**Comment by tonai** [comment]
Thanks :+1:

**Comment by norin89** [comment]
@tonai any plans for a new release to make this and other merged PRs available on NPM?

**Comment by tonai** [comment]
Hello @norin89 , yes I am planning to release a new version this weekend.

**Comment by tonai** [comment]
A little late sorry, but new version 6.1.0 has been released :)

**Pull request merged**
